# Generated by Django 6.0 on 2025-12-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('lessonType', models.CharField(choices=[('1_TO_1', '1 to 1'), ('FOCUS_GROUP', 'Focus Group')], max_length=12)),
                ('yearGroup', models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], max_length=2)),
                ('desc', models.TextField()),
            ],
        ),
    ]
