# Generated by Django 6.0 on 2025-12-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactticket',
            name='yearGroup',
            field=models.CharField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], max_length=2),
        ),
    ]
