# Generated by Django 6.0 on 2026-01-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactticket_yeargroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactticket',
            name='yearGroup',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2),
        ),
    ]
