# Generated by Django 6.0 on 2026-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactticket_yeargroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
